# Generated by Django 4.2.5 on 2023-11-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='myphotos',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Мои фото', 'verbose_name_plural': 'Мои фото'},
        ),
        migrations.AlterField(
            model_name='myphotos',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='photos.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='myphotos',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='myphotos',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='myphotos',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='myphotos',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='photos.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='myphotos',
            index=models.Index(fields=['time_create'], name='photos_myph_time_cr_5f5b0a_idx'),
        ),
    ]
